name: Terraform Plan

on:
  pull_request:
    branches: [main]

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0
      - name: Configure GCP Credentials
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan -var-file="environments/{env:env}/terraform.tfvars"
        run: terraform plan -out=plan.tfout
      - name: Comment Plan on PR
        uses: actions/github-script@v7
        with:
          script: |
            const output = await exec.exec('terraform', ['show', '-no-color', 'plan.tfout']);
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Terraform Plan:\n\`\`\`\n${output}\n\`\`\``
            });