apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ghost
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-username/origoss-assignment-repo.git'
    targetRevision: HEAD
    path: 'k8s/overlays/{{env}}/ghost'  # Use Kustomize overlay per env
    kustomize: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ghost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true